---
- name: Building justai-db01
  vmware_guest:
    validate_certs: no
    name: justai-db01
    template: Centos7
    disk:
    - size_gb: 50
      type: thin
      datastore: datastore2
    - size_gb: 30
      type: thin
      datastore: datastore2
    networks:
    - name: BridgedNetwork
      type: dhcp
    - name: VM Network
      type: static
      ip: 192.168.30.112
      netmask: 255.255.255.0
      gateway: 192.168.30.1
    hardware:
      memory_mb: 1024
      num_cpus: 2
      scsi: paravirtual
