---
- name: Building justai-db01
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: justai-lab
    cluster: cluster
    validate_certs: no
    state: poweredon
    name: justai-db01
    template: Centos7
    disk:
    - size_gb: 50
      type: thin
      datastore: datastore2
    - size_gb: 30
      type: thin
      datastore: datastore2
    networks:
    - name: BridgedNetwork
      type: dhcp
    - name: VM Network
      type: static
      ip: 192.168.30.112
      netmask: 255.255.255.0
      gateway: 192.168.30.1
    hardware:
      memory_mb: 1024
      num_cpus: 2
      scsi: paravirtual
  delegate_to: localhost
  register: deploy
  when: uuid|failed

- name: Ensure SCM code master - justai-db01
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: justai-lab
    cluster: cluster
    validate_certs: no
    state: present
    name: justai-db01
    uuid: 423c8cf2-4b7b-078e-901f-938ae495eea2
    disk:
    - size_gb: 50
      type: thin
      datastore: datastore2
    - size_gb: 30
      type: thin
      datastore: datastore2
    networks:
    - name: BridgedNetwork
      type: dhcp
    - name: VM Network
      type: static
      ip: 192.168.30.112
      netmask: 255.255.255.0
      gateway: 192.168.30.1
    hardware:
      memory_mb: 1024
      num_cpus: 2
      scsi: paravirtual
  delegate_to: localhost
